#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Structural config (this box's UID/GID, filesystem layout) — NOT secrets.
# ./host_config.env is gitignored and not committed; this repo's public
# interface is just "provide a file matching example.env's shape here" —
# PUID/PGID/DATA_ROOT/MEDIA_ROOT/CONNECTIVITY_PROJECT_ID/
# MEDIA_ACCOUNTS_PROJECT_ID/MEDIA_SELFHOSTED_PROJECT_ID, bare names,
# nothing else. This script has no idea how that file got populated: a
# forker writes it by hand from
# example.env; for this operator it's generated by
# dahome_private_config/hosts/stack-launch.sh, which is the one place
# that repo's prefixed naming convention gets translated away. Either
# way this script only ever sees the bare contract.
set -a
source "${SCRIPT_DIR}/host_config.env"
set +a
# TZ is intentionally not handled here — it has its own inline default
# (${TZ:-America/New_York}) directly in media.compose.yaml, overridable via
# Compose's own auto-loaded .env in this directory if wanted. Unrelated to
# this file or to Infisical.

# Bootstrap credential — the LaunchMedia-stack identity's own auth to
# Infisical (NOT in Git, lives only on this VM, regenerated on rebuild).
source ~/.secrets/infisical.env

export INFISICAL_TOKEN
INFISICAL_TOKEN=$(infisical login \
  --method=universal-auth \
  --client-id="${LAUNCHMEDIA_STACK_CLIENT_ID}" \
  --client-secret="${LAUNCHMEDIA_STACK_CLIENT_SECRET}" \
  --domain="${INFISICAL_API_URL}" \
  --silent --plain)

# CONNECTIVITY_PROJECT_ID and MEDIA_ACCOUNTS_PROJECT_ID come straight out
# of the sourced host_config.env above (bare names, per example.env) —
# already set, nothing to remap here.

# Each path captured into a variable (not eval'd directly from the
# substitution) so a failed export trips `set -e` instead of silently
# starting containers with missing/empty secrets.
PROTONVPN_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${CONNECTIVITY_PROJECT_ID}" \
  --env=prod \
  --path=/protonvpn/ \
  --format=dotenv-export)
eval "$PROTONVPN_SECRETS"

PLEX_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${MEDIA_ACCOUNTS_PROJECT_ID}" \
  --env=prod \
  --path=/plex/ \
  --format=dotenv-export)
eval "$PLEX_SECRETS"

MAM_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${MEDIA_ACCOUNTS_PROJECT_ID}" \
  --env=prod \
  --path=/mam/seedboxmedia/ \
  --format=dotenv-export)
eval "$MAM_SECRETS"

# No alias indirection needed for the three secrets above — unlike the MCP
# servers, docker compose just reads ${VAR} directly, and the Infisical
# key names are already chosen to match what media.compose.yaml expects
# (WIREGUARD_PRIVATE_KEY, WIREGUARD_ADDRESSES, VPN_SERVICE_PROVIDER,
# VPN_TYPE, SERVER_COUNTRIES, PLEX_CLAIM, MAM_ID).

# sonarr/ and radarr/ both export a bare API_KEY (the folder is what
# disambiguates "whose key" — same convention as TOKEN_NAME/TOKEN_SECRET
# reused across proxmox/unifi), so unlike the three exports above, each
# one here has to be captured into its disambiguated name immediately —
# otherwise radarr's eval would silently clobber sonarr's API_KEY before
# either ever reaches docker compose.
SONARR_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${MEDIA_SELFHOSTED_PROJECT_ID}" \
  --env=prod \
  --path=/sonarr/ \
  --format=dotenv-export)
eval "$SONARR_SECRETS"
export SONARR_API_KEY="${API_KEY}"

RADARR_SECRETS=$(infisical export \
  --domain="${INFISICAL_API_URL}" \
  --projectId="${MEDIA_SELFHOSTED_PROJECT_ID}" \
  --env=prod \
  --path=/radarr/ \
  --format=dotenv-export)
eval "$RADARR_SECRETS"
export RADARR_API_KEY="${API_KEY}"

cd "${SCRIPT_DIR}"
# Idempotent (inspect-or-create) — safe to run on every launch, closes the
# "two manual commands" gap for a from-scratch redeploy.
./network.sh
exec docker compose -f media.compose.yaml up -d
